version: '2'

services:
  packet-forwarder:
    image: jonzky/hm-pktfwd:latest
    depends_on:
      - helium-miner
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
    cap_add:
      - SYS_RAWIO
    networks:
      - helium
    privileged: true
    restart: unless-stopped  
    volumes:
      - pktfwdr:/var/pktfwd
    environment:
      - FIRMWARE_VERSION=2022.01.12.1
      - VARIANT=NEBHNT-OUT1
      - OVERRIDE_PKT_CONFIG_URL=https://jonzky.com/pkt.config
      - CONCENTRATOR_RESET_PIN=23

  helium-miner:
    image: jonzky/hm-miner:latest
    depends_on:
      - diagnostics
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
      - "4467:4467/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/spidev0.0:/dev/spidev0.0
    restart: on-failure
    networks:
      - helium
    environment:
      - FIRMWARE_VERSION=2022.01.12.1
      - VARIANT=NEBHNT-OUT1
      - OVERRIDE_CONFIG_URL=https://jonzky.com/miner.config

  diagnostics:
    image: jonzky/hm-diag:latest
    environment:
      - FIRMWARE_VERSION=2022.01.12.1
      - DIAGNOSTICS_VERSION=latest
      - VARIANT=NEBHNT-OUT1
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - /sys:/sys:ro
      - /lib/modules:/lib/modules:ro
      - /proc:/proc
    ports:
      - "80:5000"
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
    networks:
      - helium
    privileged: true

  cadvisor:
    image: unibaktr/cadvisor:0.39.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id/:/etc/machine-id:ro
    devices:
      - /dev/kmsg:/dev/kmsg:ro
    ports:
      - "8080:8080"
    networks:
      - helium
    restart: unless-stopped

networks:
  helium:
   driver: bridge
   ipam:
    config:
     - subnet: 172.16.57.0/24

volumes:
  miner-storage:
  miner-log:
  pktfwdr: